// react-app/src/components/Board.js
import Box from "./Box";
import "../styles/Board.css";
import { useState, useEffect } from "react";

export default function Board() {
  const [boxes, setBoxes] = useState(Array(9).fill(null));
  const [tour, setTour] = useState(true);
  const [message, setMessage] = useState("");
  const [winner, setWinner] = useState("");

  const winGame = (boxes) => {
    const winComb = [
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],
      [0, 3, 6],
      [1, 4, 7],
      [2, 5, 8],
      [0, 4, 8],
      [2, 4, 6],
    ];

    for (let i = 0; i < winComb.length; i++) {
      const [a, b, c] = winComb[i];
      if (boxes[a] && boxes[a] === boxes[b] && boxes[b] === boxes[c]) {
        return boxes[a];
      }
    }

    return null;
  };

  useEffect(() => {
    setWinner(winGame(boxes));
    let remainingBoxes = boxes.filter((x) => x == null).length;

    if (winner) {
      setMessage(winner + " wins");
    } else if (remainingBoxes === 0) {
      setMessage("Tie");
    }
  }, [boxes, winner]);

  const handleClick = (i) => {
    if (winner) {
      return null;
    }

    const values = boxes.slice();

    tour ? (values[i] = "X") : (values[i] = "O");
    setBoxes(values);
    setTour(!tour);
  };

  const renderBox = (i) => {
    return <Box value={boxes[i]} onClick={() => handleClick(i)} />;
  };

  const replay = () => {
    setBoxes(Array(9).fill(null));
    setWinner("");
    setMessage("");
  };
  return (
    <>
      <div className="board">
        <div className="board-row">
          {renderBox(0)}
          {renderBox(1)}
          {renderBox(2)}
        </div>
        <div className="board-row">
          {renderBox(3)}
          {renderBox(4)}
          {renderBox(5)}
        </div>
        <div className="board-row">
          {renderBox(6)}
          {renderBox(7)}
          {renderBox(8)}
        </div>
      </div>
      {message ? (
        <div className="win-tag">
          <h3 className="winner">{message}</h3>
          <button onClick={replay} className="replay-btn">
            Replay
          </button>
        </div>
      ) : (
        <></>
      )}
    </>
  );
}

// angular-app/src/app/components/board/board.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-board',
  templateUrl: './board.component.html',
  styleUrls: ['./board.component.css']
})
export class BoardComponent implements OnInit {
  squares:any[] = Array(9);
  isNext : boolean ;
  winner : string | null ;
  get player() {
    return this.isNext ? 'X':'O'
  }

  playNext(i:number):void{
   
    if(!this.squares[i] && !this.winner){
      this.squares.splice(i,1,this.player)
      console.log(this.squares)
      this.isNext = !this.isNext
    }

    this.winner  = this.winGame(this.squares)
    let empty = this.squares.filter(val => val === null).length ;
    
    if(this.winner){
      this.winner = this.winner + " wins"
    }
    if(empty == 0 && !this.winner){
      this.winner = "Tie"
    }
  }


  winGame = (squares:any[]):string|null => {
    const winComb = [
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],
      [0, 3, 6],
      [1, 4, 7],
      [2, 5, 8],
      [0, 4, 8],
      [2, 4, 6],
    ];

    for (let i = 0; i < winComb.length; i++) {
      const [a, b, c] = winComb[i];
      if (squares[a] && squares[a] === squares[b] && squares[b] === squares[c]) {
        return squares[a];
      }
    }

    return null;
  };

  replay():void{
    this.ngOnInit()
  }

  ngOnInit(): void {
      this.squares.fill(null)
      this.isNext = true;
      this.winner = null
  }
}

<div class="container">
    <div class="main">
        <app-square  *ngFor = "let val of squares; let i = index" [value] ="val" (handleClick)="playNext(i)"></app-square>
    </div>
    <div *ngIf = "winner" class="winner">
       <h3>{{winner}}</h3>
       <button (click) = "replay()">replay</button>
    </div>    
</div>
